name : Firebase Deployment


on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deployment
    runs-on : ubuntu-latest

    steps:
      - name : get the source code
        uses: actions/checkout@v2

      - name : install node
        uses: actions/setup-node@v2
        with:
            node-version: '14'

      - name : install node packages
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: false
      
      - name : Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          REACT_APP_YOUTUBE_API_KEY3: ${{secrets.REACT_APP_YOUTUBE_API_KEY3}}